version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulsestack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  oracle-indexer:
    build:
      context: .
      dockerfile: Dockerfile.oracle
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pulsestack
      - ORACLE_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - TELEMETRY_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
